aws_region        = "us-east-2"
project_name      = "CareerVault"
environment       = "production"
ami_id            = "ami-0c02fb55956c7d316"  # Amazon Linux 2 AMI (HVM) - us-east-2
instance_type     = "t3.medium"
db_instance_type  = "t3.small"
min_size          = 1
max_size          = 3
desired_capacity  = 2
gemini_api_key    = "your-gemini-api-key-here"  # Replace with your actual API key
key_pair_name     = ""  # Optional: Add your EC2 key pair name for SSH access
