version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: careervault-backend
    ports:
      - "8000:8000"  # Backend API accessible on localhost:8000
    environment:
      - GEMINI_API_KEY=AIzaSyBeWdCT_E-wFw4ZinGb6QWZpqZnOc_Jcxc
      - MONGO_URL=mongodb://mongo:27017/careervault
    depends_on:
      - mongo

  frontend:
    build:
      context: ./vite-project
      dockerfile: Dockerfile
    container_name: careervault-frontend
    ports:
      - "3000:80"  # Frontend accessible on localhost:3000
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: careervault-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: careervault
    ports:
      - "27017:27017" # MongoDB accessible on localhost:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
